"""initial schema with 14 tables

Revision ID: 27ea50ad4a4a
Revises: 
Create Date: 2026-09-22 08:52:16.701085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27ea50ad4a4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Human-readable source name'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='structured_db | document_store | api | communication'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the source'),
    sa.Column('connection_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Flexible connection metadata (host, credentials ref, etc.)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this source is currently active'),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Extra source-specific metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(length=500), nullable=False, comment='Short human-readable title of the task'),
    sa.Column('description', sa.Text(), nullable=False, comment='Raw task description as submitted by the user'),
    sa.Column('use_case', sa.String(length=100), nullable=True, comment='Use case identifier (e.g., supplier_qualification, purchase_delay)'),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='Current status: pending, processing, ready, under_review, approved, rejected, completed'),
    sa.Column('intent', sa.String(length=100), nullable=True, comment='Extracted task intent (e.g., investigate, resolve, verify)'),
    sa.Column('task_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Flexible metadata: priority, source hints, custom fields'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Event identifier, e.g., 'task.created', 'package.approved'"),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment="Type of the entity involved, e.g., 'task', 'package'"),
    sa.Column('entity_id', sa.Uuid(), nullable=True, comment='ID of the specific entity involved (no FK; entity may be deleted)'),
    sa.Column('task_id', sa.UUID(), nullable=True, comment='Convenience FK to tasks (for task-level queries and indexing). Unlike entity_type/entity_id (which are polymorphic and have no FK), this is a real FK. ON DELETE SET NULL ensures the audit log survives task deletion while preserving the linkage until then.'),
    sa.Column('actor', sa.String(length=100), nullable=True, comment='Actor identifier. NULL until auth is implemented.'),
    sa.Column('severity', sa.String(length=20), server_default='info', nullable=False, comment='info | warning | error'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Event-specific payload'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this event occurred (immutable)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_task_id'), 'audit_logs', ['task_id'], unique=False)
    op.create_table('operational_packages',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this package belongs to'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='Version number (increments on re-generation)'),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False, comment='draft | ready_for_review | approved | rejected | superseded'),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='The 11 structured sections of the package'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Short LLM-generated summary of the package'),
    sa.Column('generated_by', sa.String(length=50), server_default='system', nullable=False, comment="Generator identifier (e.g., 'system', 'system+v1.2.0')"),
    sa.Column('package_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Prompt version, tokens used, generation time, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'version', name='uq_operational_packages_task_version')
    )
    op.create_index(op.f('ix_operational_packages_status'), 'operational_packages', ['status'], unique=False)
    op.create_index(op.f('ix_operational_packages_task_id'), 'operational_packages', ['task_id'], unique=False)
    op.create_table('source_records',
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Source this record belongs to'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment="Source system's own identifier (e.g., S-1042, PO-4821)"),
    sa.Column('record_type', sa.String(length=100), nullable=False, comment='Record type: supplier, purchase_order, certificate, policy, etc.'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='The actual record data (use-case specific schema)'),
    sa.Column('record_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Extra metadata: fetch time, ingestion info, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_records_source_external_id')
    )
    op.create_index(op.f('ix_source_records_record_type'), 'source_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_source_records_source_id'), 'source_records', ['source_id'], unique=False)
    op.create_index('ix_source_records_source_type', 'source_records', ['source_id', 'record_type'], unique=False)
    op.create_table('task_requirements',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this requirement belongs to'),
    sa.Column('requirement_type', sa.String(length=100), nullable=False, comment='Type: financial_info, compliance_cert, quality_history, etc.'),
    sa.Column('description', sa.Text(), nullable=False, comment="Human-readable description of what's needed"),
    sa.Column('is_mandatory', sa.Boolean(), server_default='true', nullable=False, comment='Whether this requirement must be satisfied'),
    sa.Column('source_hint', sa.String(length=200), nullable=True, comment='Optional hint on which source to use'),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False, comment='Priority order (1 = highest)'),
    sa.Column('requirement_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Extra metadata about the requirement'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_requirements_task_id'), 'task_requirements', ['task_id'], unique=False)
    op.create_table('correlations',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this correlation is part of'),
    sa.Column('record_a_id', sa.UUID(), nullable=False, comment='First record in the relationship'),
    sa.Column('record_b_id', sa.UUID(), nullable=False, comment='Second record in the relationship'),
    sa.Column('relationship_type', sa.String(length=100), nullable=False, comment='e.g., supplier_has_purchase_order'),
    sa.Column('basis', sa.String(length=50), nullable=False, comment='exact_id | business_key | semantic'),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False, comment='Trust/strength score for this correlation. 1.0 = deterministic (fully trusted). Lower values = less certain (semantic). Range: 0.0 - 1.0'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='Whether a human has verified this correlation. Actor/timestamp captured in audit log, not here.'),
    sa.Column('correlation_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Matching values, evidence, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_correlations_confidence_range'),
    sa.CheckConstraint('record_a_id <> record_b_id', name='ck_correlations_no_self_reference'),
    sa.ForeignKeyConstraint(['record_a_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_b_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'record_a_id', 'record_b_id', 'relationship_type', name='uq_correlations_task_pair_type')
    )
    op.create_index(op.f('ix_correlations_record_a_id'), 'correlations', ['record_a_id'], unique=False)
    op.create_index(op.f('ix_correlations_record_b_id'), 'correlations', ['record_b_id'], unique=False)
    op.create_index(op.f('ix_correlations_task_id'), 'correlations', ['task_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this review is for (denormalized for query clarity)'),
    sa.Column('package_id', sa.UUID(), nullable=False, comment='Package being reviewed (authoritative package)'),
    sa.Column('decision', sa.String(length=30), nullable=False, comment='approved | rejected | edited | info_requested'),
    sa.Column('comments', sa.Text(), nullable=True, comment='Optional human reasoning / notes'),
    sa.Column('edited_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Diff of edited sections (required when decision='edited')"),
    sa.Column('review_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Time taken, UI context, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision <> 'edited' OR edited_sections IS NOT NULL", name='ck_human_reviews_edited_requires_diff'),
    sa.ForeignKeyConstraint(['package_id'], ['operational_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_package_id'), 'human_reviews', ['package_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_task_id'), 'human_reviews', ['task_id'], unique=False)
    op.create_table('retrieved_records',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this retrieval was for'),
    sa.Column('requirement_id', sa.UUID(), nullable=True, comment='Requirement this retrieval satisfies (if applicable)'),
    sa.Column('source_record_id', sa.UUID(), nullable=False, comment='The actual source record that was retrieved'),
    sa.Column('retrieval_method', sa.String(length=50), nullable=False, comment='sql_query | vector_search | api_call | rule_based'),
    sa.Column('relevance_score', sa.Float(), nullable=True, comment='Relevance score 0.0-1.0 (if applicable)'),
    sa.Column('is_selected', sa.Boolean(), server_default='true', nullable=False, comment='Whether this record is selected for the final context'),
    sa.Column('retrieval_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Query used, time taken, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['task_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'source_record_id', name='uq_retrieved_records_task_source')
    )
    op.create_index(op.f('ix_retrieved_records_requirement_id'), 'retrieved_records', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_retrieved_records_source_record_id'), 'retrieved_records', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_retrieved_records_task_id'), 'retrieved_records', ['task_id'], unique=False)
    op.create_table('validations',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this validation belongs to'),
    sa.Column('requirement_id', sa.UUID(), nullable=True, comment='Requirement this validation relates to (if applicable)'),
    sa.Column('validation_type', sa.String(length=50), nullable=False, comment='missing_requirement | inconsistency | incomplete_context'),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=False, comment='low | medium | high'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable summary of the finding'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment="Structured details. For inconsistency, should contain 'values': [{'record_id': UUID, 'value': ..., 'source': ...}, ...] to preserve provenance of conflicting values."),
    sa.Column('status', sa.String(length=30), server_default='open', nullable=False, comment='open | acknowledged | resolved'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['task_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_requirement_id'), 'validations', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_validations_task_id'), 'validations', ['task_id'], unique=False)
    op.create_index(op.f('ix_validations_validation_type'), 'validations', ['validation_type'], unique=False)
    op.create_table('workflows',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this workflow is for'),
    sa.Column('package_id', sa.UUID(), nullable=False, comment="Approved package that initiated this workflow. IMPORTANT: The referenced package MUST have status='approved'. This invariant is enforced by the service layer (see Stage 13), not by a DB constraint."),
    sa.Column('template_name', sa.String(length=100), nullable=False, comment='Workflow template used (e.g., supplier_onboarding_v1)'),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False, comment='pending | active | completed | cancelled | failed'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of this workflow instance'),
    sa.Column('workflow_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Extra metadata (initiator context, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['operational_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_package_id'), 'workflows', ['package_id'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('ix_workflows_task_id'), 'workflows', ['task_id'], unique=False)
    op.create_table('information_requests',
    sa.Column('workflow_id', sa.UUID(), nullable=True, comment='Workflow this request belongs to. NULL if the request originated in Phase 1 (before any workflow exists).'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this request is for'),
    sa.Column('validation_id', sa.UUID(), nullable=True, comment='Validation that triggered this request (if any)'),
    sa.Column('request_type', sa.String(length=50), nullable=False, comment='missing_document | clarification | verification | other'),
    sa.Column('description', sa.Text(), nullable=False, comment='What information is being requested'),
    sa.Column('target_role', sa.String(length=100), nullable=False, comment='Role expected to respond'),
    sa.Column('status', sa.String(length=30), server_default='open', nullable=False, comment='open | responded | resolved | cancelled'),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Response payload (structure varies by request type)'),
    sa.Column('response_notes', sa.Text(), nullable=True, comment='Free-text notes from the responder'),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Extra info: deadline, priority, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_id'], ['validations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_requests_status'), 'information_requests', ['status'], unique=False)
    op.create_index(op.f('ix_information_requests_task_id'), 'information_requests', ['task_id'], unique=False)
    op.create_index(op.f('ix_information_requests_workflow_id'), 'information_requests', ['workflow_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('workflow_id', sa.UUID(), nullable=False, comment='Workflow this step belongs to'),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='Order within the workflow (for display)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Step name (e.g., 'Verify compliance certifications')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the step'),
    sa.Column('responsible_role', sa.String(length=100), nullable=True, comment="Role responsible for this step (e.g., 'compliance_officer')"),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='List of step IDs this step depends on. Stored as JSONB because steps are immutable after workflow creation and reverse dependency queries are not required in the current prototype. If reverse queries become necessary, refactor to a separate dependency table.'),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False, comment='Whether this step requires explicit approval'),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False, comment='pending | in_progress | blocked | completed | skipped | failed'),
    sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Extra info: inputs required, outputs expected, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_status'), 'workflow_steps', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('assignments',
    sa.Column('workflow_step_id', sa.UUID(), nullable=False, comment='Step being assigned'),
    sa.Column('assigned_role', sa.String(length=100), nullable=False, comment='Role responsible (e.g., procurement_manager)'),
    sa.Column('status', sa.String(length=30), server_default='assigned', nullable=False, comment='assigned | accepted | completed | declined | reassigned'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes from or for the assignee'),
    sa.Column('assignment_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Extra info: SLA, urgency, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_workflow_step_id'), 'assignments', ['workflow_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_workflow_step_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_status'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_information_requests_workflow_id'), table_name='information_requests')
    op.drop_index(op.f('ix_information_requests_task_id'), table_name='information_requests')
    op.drop_index(op.f('ix_information_requests_status'), table_name='information_requests')
    op.drop_table('information_requests')
    op.drop_index(op.f('ix_workflows_task_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_package_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_validations_validation_type'), table_name='validations')
    op.drop_index(op.f('ix_validations_task_id'), table_name='validations')
    op.drop_index(op.f('ix_validations_requirement_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_retrieved_records_task_id'), table_name='retrieved_records')
    op.drop_index(op.f('ix_retrieved_records_source_record_id'), table_name='retrieved_records')
    op.drop_index(op.f('ix_retrieved_records_requirement_id'), table_name='retrieved_records')
    op.drop_table('retrieved_records')
    op.drop_index(op.f('ix_human_reviews_task_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_package_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_correlations_task_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_record_b_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_record_a_id'), table_name='correlations')
    op.drop_table('correlations')
    op.drop_index(op.f('ix_task_requirements_task_id'), table_name='task_requirements')
    op.drop_table('task_requirements')
    op.drop_index('ix_source_records_source_type', table_name='source_records')
    op.drop_index(op.f('ix_source_records_source_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_record_type'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_operational_packages_task_id'), table_name='operational_packages')
    op.drop_index(op.f('ix_operational_packages_status'), table_name='operational_packages')
    op.drop_table('operational_packages')
    op.drop_index(op.f('ix_audit_logs_task_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('tasks')
    op.drop_table('sources')
    # ### end Alembic commands ###
