"""add policy_chunks with pgvector

Revision ID: 7bbc8b40b1a3
Revises: 27ea50ad4a4a
Create Date: 2026-09-25 10:02:50.677541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '7bbc8b40b1a3'
down_revision: Union[str, None] = '27ea50ad4a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension first (idempotent)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'policy_chunks',
        sa.Column(
            'source_record_id',
            sa.UUID(),
            nullable=False,
            comment='Parent policy document (source_record)',
        ),
        sa.Column(
            'chunk_index',
            sa.Integer(),
            nullable=False,
            comment='Zero-based order of this chunk within the document',
        ),
        sa.Column(
            'chunk_text',
            sa.Text(),
            nullable=False,
            comment='Actual chunk content (used for lexical + context display)',
        ),
        sa.Column(
            'embedding',
            pgvector.sqlalchemy.Vector(dim=1024),
            nullable=False,
            comment='Dense embedding (dimension from app.embeddings.base)',
        ),
        sa.Column(
            'chunk_metadata',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{}',
            nullable=False,
            comment='Provider, model, version, timestamps for re-embedding',
        ),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['source_record_id'],
            ['source_records.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'source_record_id',
            'chunk_index',
            name='uq_policy_chunks_source_chunk',
        ),
    )
    op.create_index(
        op.f('ix_policy_chunks_source_record_id'),
        'policy_chunks',
        ['source_record_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_policy_chunks_source_record_id'),
        table_name='policy_chunks',
    )
    op.drop_table('policy_chunks')
    # ### end Alembic commands 